version: "3.3"
services:
  courtbot:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: openboise/courtbot:latest
    volumes:
      - ${PWD}/courtbot.exs:/opt/app/etc/courtbot.exs
      - ${PWD}/wait-for-postgres.sh:/tmp/wait-for-postgres.sh
    ports:
      - "4001:4000"
    command: ["/tmp/wait-for-postgres.sh", "/opt/app/bin/courtbot foreground"]
    links:
      - postgres
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courtbot
    image: postgres:10
    ports:
      - "5434:5432"


